# Generated by Django 5.2.9 on 2026-01-04 04:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('name', models.CharField(blank=True, help_text='用户真实姓名或昵称', max_length=50, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', help_text='用户性别', max_length=10, null=True, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, db_index=True, help_text='用户手机号码，用于登录和找回密码', max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('avatar_url', models.URLField(blank=True, help_text='用户头像图片 URL', max_length=500, null=True, verbose_name='头像链接')),
                ('birthday', models.DateField(blank=True, help_text='用户出生日期', null=True, verbose_name='出生日期')),
                ('bio', models.TextField(blank=True, help_text='用户个人简介或签名', max_length=500, null=True, verbose_name='个人简介')),
                ('address', models.CharField(blank=True, help_text='用户联系地址', max_length=200, null=True, verbose_name='联系地址')),
                ('id_card', models.CharField(blank=True, db_index=True, help_text='用户身份证号码（加密存储）', max_length=18, null=True, verbose_name='身份证号')),
                ('wechat_openid', models.CharField(blank=True, db_index=True, help_text='微信小程序/公众号 OpenID', max_length=100, null=True, unique=True, verbose_name='微信OpenID')),
                ('wechat_unionid', models.CharField(blank=True, db_index=True, help_text='微信开放平台 UnionID', max_length=100, null=True, unique=True, verbose_name='微信UnionID')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='用户最后一次登录的 IP 地址', null=True, verbose_name='最后登录IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['mobile'], name='idx_user_mobile'), models.Index(fields=['wechat_openid'], name='idx_user_wechat_openid'), models.Index(fields=['create_time'], name='idx_user_create_time')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
