# Generated by Django 5.2.9 on 2026-01-04 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('all', '全平台')], default='all', help_text='应用平台类型', max_length=20, verbose_name='平台')),
                ('version_code', models.IntegerField(db_index=True, help_text='版本号（整数），用于版本比较，例如：100、101、200', verbose_name='版本号')),
                ('version_name', models.CharField(help_text='版本名称（字符串），例如：1.0.0、1.0.1', max_length=50, validators=[django.core.validators.RegexValidator(message='版本名称格式必须为：x.x.x（例如：1.0.0）', regex='^\\d+\\.\\d+\\.\\d+$')], verbose_name='版本名称')),
                ('title', models.CharField(help_text='版本更新的标题', max_length=200, verbose_name='更新标题')),
                ('description', models.TextField(help_text='版本更新的详细描述，支持换行', verbose_name='更新描述')),
                ('download_url', models.URLField(blank=True, help_text='应用下载链接（APK/IPA 或应用商店链接）', max_length=500, null=True, verbose_name='下载地址')),
                ('is_force_update', models.BooleanField(default=False, help_text='强制更新时，用户必须更新才能继续使用应用', verbose_name='是否强制更新')),
                ('is_active', models.BooleanField(default=True, help_text='只有启用的版本才会被检查接口返回', verbose_name='是否启用')),
                ('release_notes', models.TextField(blank=True, help_text='详细的更新日志，支持 Markdown 格式', null=True, verbose_name='更新日志')),
                ('min_support_version', models.IntegerField(blank=True, help_text='低于此版本号的应用将被强制更新', null=True, verbose_name='最低支持版本号')),
            ],
            options={
                'verbose_name': '应用版本',
                'verbose_name_plural': '应用版本管理',
                'db_table': 'setting_app_version',
                'ordering': ['-version_code', '-create_time'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='setting_app_platfor_abf1a6_idx'), models.Index(fields=['-version_code'], name='setting_app_version_bee818_idx')],
                'unique_together': {('platform', 'version_code')},
            },
        ),
    ]
