# Generated by Django 5.2.9 on 2026-01-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('delete_time', models.DateTimeField(blank=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('type', models.CharField(choices=[('banner', 'Banner广告'), ('activity', '活动配置'), ('setting', '系统设置')], db_index=True, help_text='配置类型：banner、activity、setting', max_length=50, verbose_name='配置类型')),
                ('title', models.CharField(help_text='配置项的标题', max_length=200, verbose_name='标题')),
                ('banner_image_url', models.URLField(blank=True, help_text='Banner图片地址，用于 banner 和 activity 类型', max_length=500, null=True, verbose_name='Banner图片URL')),
                ('target_url', models.URLField(blank=True, help_text='点击后跳转的网页地址', max_length=500, null=True, verbose_name='目标URL')),
                ('description', models.TextField(blank=True, help_text='配置项的详细描述', null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(db_index=True, default=0, help_text='数字越小越靠前，默认为0', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='只有启用的配置才会被接口返回', verbose_name='是否启用')),
                ('start_time', models.DateTimeField(blank=True, help_text='配置生效的开始时间', null=True, verbose_name='生效开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='配置生效的结束时间', null=True, verbose_name='生效结束时间')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='额外的配置数据，JSON格式', null=True, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '动态配置',
                'verbose_name_plural': '动态配置管理',
                'db_table': 'setting_dynamic_config',
                'ordering': ['type', 'sort_order', '-create_time'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='setting_dyn_type_19b6f6_idx'), models.Index(fields=['type', 'sort_order'], name='setting_dyn_type_0d479b_idx'), models.Index(fields=['start_time', 'end_time'], name='setting_dyn_start_t_00b573_idx')],
            },
        ),
    ]
